#define CHORDAL_HOLD
#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "JRZ6Q/qm6p44"
#define LAYER_STATE_8BIT

#define AUTOMOUSE_LAYER 5
#define AUTOMOUSE_THRESHOLD 10
#define RGB_MATRIX_STARTUP_SPD 60

